stages:
  - checkout
  - build
  - archive

variables:
  CONAN_USER: "ess-dmsc"
  CONAN_PKG_CHANNEL: "stable"
  PROJECT_NAME: "conan-epics"
  NUM_ARTIFACTS_TO_KEEP: 1

before_script:
  - echo "Setting up environment..."
  - |
    if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then
      export NUM_ARTIFACTS_TO_KEEP=3
    else
      export NUM_ARTIFACTS_TO_KEEP=1
    fi

# Cache Conan dependencies
cache:
  paths:
    - .conan

# macOS Build Stage (if enabled)
macos_build:
  stage: build
  tags:
    - dc-zone
  image: apple/Xcode:latest
  script:
    - |
      rm -rf $PROJECT_NAME  # Clean up previous clone if any
      git clone https://gitlab.esss.lu.se/ecdc/ess-dmsc/conan-epics.git
      cd $PROJECT_NAME
      git checkout $CI_COMMIT_REF_NAME

      # macOS: Package
      conan create . ${CONAN_USER}/${CONAN_PKG_CHANNEL} --build=outdated
  only:
    - master
  artifacts:
    paths:
      - build/
    expire_in: 1 day

# Archiving Build Node
archiving:
  stage: archive
  tags:
    - dc-zone 
  image: centos:7
  script: |
    # No sudo needed, run as the default user
    echo "Installing dependencies..."
    
    # Fix CentOS repository issue
    sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Base.repo
    sed -i 's/^#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/mirror.centos.org\/centos\/7\/os\/x86_64\/' /etc/yum.repos.d/CentOS-Base.repo

    # Update and install required packages
    yum update -y
    yum install -y curl centos-release-scl rh-python38

    # Enable devtoolset and install pip
    scl enable rh-python38 devtoolset-11 bash << 'INNER_EOF'
      # Install pip
      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      python get-pip.py

      # Install Conan
      pip install conan==1.65
    INNER_EOF

    # STAGE::Archive 
    cd archiving/epics
    touch BUILD_INFO
    echo 'Repository: ${pipelineBuilder.project}/${env.BRANCH_NAME}' >> BUILD_INFO
    echo 'Commit: ${scmVars.GIT_COMMIT}' >> BUILD_INFO
    echo 'Jenkins build: ${env.BUILD_NUMBER}' >> BUILD_INFO
    #conan create . ess-dmsc/stable --build=outdated
    
    #TODO: 
    #conan user --password '\'****\'' --remote ecdc-conan-release ecdc
    #conan upload epics/x.y.z-dm1@ess-dmsc/stable --remote alias_of_repository
    cd archiving
    ./generate-conanfile.sh "${CONAN_USER}" "${CONAN_PKG_CHANNEL}" 
    cat conanfile.txt
    mkdir epics
    cd epics
    conan install ..
    touch BUILD_INFO
    echo "Repository: $CI_PROJECT_NAME/$CI_COMMIT_REF_NAME" >> BUILD_INFO
    echo "Commit: $CI_COMMIT_SHA" >> BUILD_INFO
    echo "GitLab build: $CI_JOB_ID" >> BUILD_INFO
    tar czvf epics.tar.gz epics

  artifacts:
    paths:
      - epics.tar.gz
    expire_in: 1 day

# Clean up after the build
after_script:
  - echo "Cleaning workspace"
  - rm -rf $CI_PROJECT_DIR
